-- DROP TABLE IF EXISTS USER;
--
-- CREATE TABLE IF NOT EXISTS USER (
--   id INTEGER AUTO_INCREMENT NOT NULL ,
--   name VARCHAR(128),
--   PRIMARY KEY (id)
-- );

INSERT INTO USER (id, name) VALUES (1, '뚱2');